### ISSUE TITLE
`use_fast_cpp_protos=true` on MacOS Arm64

### ISSUE THREAD

**Issue by rstz** [pybind/pybind11_protobuf#173]
Hi,

I'm trying to restore MacOS support for [Yggdrasil Decision Forests](https://github.com/google/yggdrasil-decision-forests), which proves more challenging than expected. As a first step, I tried running the tests in this repository under MacOS 14.5 (Arm64 architecture).

However, simply adding `build --define=use_fast_cpp_protos=true` to the project's `.bazelrc` makes tests fail with
```
# Configuration: 0d5ebff10b22bfda3f3ae92bd192687fc16f9a19af7749ad3686c9e0dd13d0b1
# Execution platform: @@platforms//host:host

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
Undefined symbols for architecture arm64:
  "_PyModule_AddIntConstant", referenced from:
      _PyInit__api_implementation in api_implementation.o
  "_PyModule_Create2", referenced from:
      _PyInit__api_implementation in api_implementation.o
  "__Py_Dealloc", referenced from:
      _Py_DECREF(_object*) in api_implementation.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

The issue happens with all Python versions. Is this a known issue on MacOS?

**Comment by rwgk** [comment]
> `--define=use_fast_cpp_protos=true`

AFAIK the protobuf team is working towards completely removing OSS support for that feature. The feature was never really supported in pybind11_protobuf OSS.

See also: https://github.com/pybind/pybind11_protobuf/pull/161#issuecomment-2176991293

The linker error looks more general, macOS has general issues around undefined symbols from the Python runtime library. I don't have full context there, just saying it's not surprising at first sight.

What happens if you simply don't try to use `use_fast_cpp_protos`? (Does that sidestep the linker error?)

**Comment by rstz** [comment]
Thank you for explaining. Removing `use_fast_cpp_protos` sidesteps the error, so I'll see if I can also remove the flag from our library.
